name: responsive_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
